Section A: Data Structures & Control Structures

1

In [63]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [64]:
list.append(6)
list
### add element 6 to list

[1, 2, 3, 4, 5, 6]

In [65]:
list.extend([2,7])
list
### add multiple elements to list

[1, 2, 3, 4, 5, 6, 2, 7]

In [66]:
list.insert(2,9)
list
### insert 9 in index 2 of the list

[1, 2, 9, 3, 4, 5, 6, 2, 7]

In [67]:
list.remove(9)
list
### removing first occurance of 9

[1, 2, 3, 4, 5, 6, 2, 7]

In [68]:
list.pop()
list
### remove the last element of the list

[1, 2, 3, 4, 5, 6, 2]

In [69]:
list1=list.copy()
list1

[1, 2, 3, 4, 5, 6, 2]

In [70]:
list1.clear()
list1
### clear the list1

[]

In [71]:
list.index(4)
### print the index of the given number

3

In [73]:
list.count(2)
### print the count of given number

2

In [75]:
list.sort()
list
### sort the list in ascending order

[1, 2, 2, 3, 4, 5, 6]

In [76]:
list.reverse()
list
### reverse the given list

[6, 5, 4, 3, 2, 2, 1]

2

In [77]:
students=["athul","aswin","charun"]
students
### create a tuple called students add 3 name
### a tuple is immutable so chance can't be done

['athul', 'aswin', 'charun']

3

In [78]:
set={1,2,3,4,1,2,5,6,7,8,9,5}
set
### set automatically delete duplicate elements

{1, 2, 3, 4, 5, 6, 7, 8, 9}

4

In [79]:
student={'name': 'athul','age': 25,'city': 'thrissur'}
student
### create a dictionary called student and  add keys: name, age, city

{'name': 'athul', 'age': 25, 'city': 'thrissur'}

In [80]:
student['age']=22
student['email']='athul@gamil.com'
student
### update age and add new  key email

{'name': 'athul', 'age': 22, 'city': 'thrissur', 'email': 'athul@gamil.com'}

5

In [82]:
age=int(input("enter the age: "))
if age>=18:
    print("eligible for voting")
else:
    print("not eligible for voting")
### check the eligiblity of age


enter the age: 25
eligible for voting


6

In [86]:
mark=int(input("enter the mark: "))
if mark>=90:
    print("grade A")
elif mark>=75 and mark<90:
    print("grade B")
elif mark>=50 and mark<75:
    print("grade C")
elif mark<50:
    print("fail")
### check the grade of mark



enter the mark: 75
grade B


7

In [88]:
num=int(input("enter the number: "))
if num>0:
  if num%2==0:
    print("positive even number")
  else:
    print("positive odd number")
elif num<0:
  print("negative number")
elif num==0:
  print("zero")
### check the number is positive or negative or zero


enter the number: 0
zero


Section B: Numpy

8


In [89]:
import numpy as np
scalar=np.array(5)
scalar
### create a scalar

array(5)

In [91]:
array_1d= np.array([1,2,3,4,5])
array_1d
### Create a 1D array with values 1 to 5

array([1, 2, 3, 4, 5])

In [93]:
array_2d= np.arange(10,70,10).reshape(2,3)
array_2d
### Create a 2D array with shape (2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

9

In [95]:
random=np.random.randint(0,101,size=(4,4))
random
### Create a 2D array with random values

array([[11, 36, 67, 47],
       [53, 34, 14,  8],
       [53, 52, 71, 11],
       [47, 38, 69, 16]])

10

In [103]:
import pandas as pd
array_2D = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
### Create a 3x3 NumPy array
df=pd.DataFrame(array_2D, columns=['A','B','C'])
df
### Convert to DataFrame with column names

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Section C: Exploring Pandas

11

In [106]:
data = {
    'Name': ['Amit', 'Neha', 'Raj', 'Priya', 'Amit', 'Sonia', 'Vikram', 'Rita', 'Neha', 'Karan'],
    'Age': [25, 30, 22, 28, 25, 35, 40, 26, 30, 29],
    'City': ['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Delhi', 'Pune', 'Bangalore', 'Hyderabad', 'Mumbai', 'Pune'],
    'Salary': [50000, 60000, np.nan, 55000, 50000, 70000, 80000, np.nan, 60000, 65000]
}
df = pd.DataFrame(data)
df
### Create a DataFrame with 10 rows

Name  Age       City   Salary
0    Amit   25      Delhi  50000.0
1    Neha   30     Mumbai  60000.0
2     Raj   22    Chennai      NaN
3   Priya   28    Kolkata  55000.0
4    Amit   25      Delhi  50000.0
5   Sonia   35       Pune  70000.0
6  Vikram   40  Bangalore  80000.0
7    Rita   26  Hyderabad      NaN
8    Neha   30     Mumbai  60000.0
9   Karan   29       Pune  65000.0

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [108]:
df.describe()

Age        Salary
count  10.000000      8.000000
mean   29.000000  61250.000000
std     5.270463  10264.362759
min    22.000000  50000.000000
25%    25.250000  53750.000000
50%    28.500000  60000.000000
75%    30.000000  66250.000000
max    40.000000  80000.000000

In [110]:
df[['Name','City']]
### selecy name and city only

Name       City
0    Amit      Delhi
1    Neha     Mumbai
2     Raj    Chennai
3   Priya    Kolkata
4    Amit      Delhi
5   Sonia       Pune
6  Vikram  Bangalore
7    Rita  Hyderabad
8    Neha     Mumbai
9   Karan       Pune

In [114]:
df1=df.drop('City',axis=1)
df1
### drop city

Name  Age   Salary
0    Amit   25  50000.0
1    Neha   30  60000.0
2     Raj   22      NaN
3   Priya   28  55000.0
4    Amit   25  50000.0
5   Sonia   35  70000.0
6  Vikram   40  80000.0
7    Rita   26      NaN
8    Neha   30  60000.0
9   Karan   29  65000.0

In [115]:
mean=df['Salary'].mean()
df.fillna(mean,inplace=True)
df
### fill salary with mean

Name  Age       City   Salary
0    Amit   25      Delhi  50000.0
1    Neha   30     Mumbai  60000.0
2     Raj   22    Chennai  61250.0
3   Priya   28    Kolkata  55000.0
4    Amit   25      Delhi  50000.0
5   Sonia   35       Pune  70000.0
6  Vikram   40  Bangalore  80000.0
7    Rita   26  Hyderabad  61250.0
8    Neha   30     Mumbai  60000.0
9   Karan   29       Pune  65000.0

In [116]:
df.drop_duplicates(inplace=True)
df
### drop duplicates

Name  Age       City   Salary
0    Amit   25      Delhi  50000.0
1    Neha   30     Mumbai  60000.0
2     Raj   22    Chennai  61250.0
3   Priya   28    Kolkata  55000.0
5   Sonia   35       Pune  70000.0
6  Vikram   40  Bangalore  80000.0
7    Rita   26  Hyderabad  61250.0
9   Karan   29       Pune  65000.0